# -*- coding: utf-8 -*-
"""find

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14igxOJzvdnEdX30j_XQget0NHtOClv1C
"""

from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException
import re
import pandas as pd

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')

wd = webdriver.Chrome('chromedriver',options=chrome_options)

def get_year(df):

    y_dict = dict()

    wd = webdriver.Chrome('chromedriver', options=chrome_options)
    google_url = 'https://www.google.com'

    for i in range(len(df)):
        
        name = df.iloc[i, 0]
        platform = df.iloc[i, 1]
        query = '{} {} released date?'.format(platform, re.sub('[\(\[].*?[\)\]]', '', name).strip())
        
        wd.get(google_url + '/search?q={}'.format(query))
        
        class_name = 'Z0LcW'

        try:
            time_element = wd.find_element_by_class_name(class_name)
            
            wait = WebDriverWait(wd, 10)

            wait.until(EC.visibility_of(time_element))

            time_text = time_element.text

            y_dict[name] = int(time_text.split()[-1])

        except Exception as e:
            pass

    wd.close()

    return y_dict


def fill_year(df, split):

    rst_dict = dict()

    df_dict = {n: df.iloc[n:n+split, :] for n in range(0, len(df), split)}

    for key in df_dict.keys():
        rst_dict.update(get_year(df_dict[key]))

    #df['Year'] = df['Name'].map(rst_dict)

    return rst_dict

def get_genre(df):

    g_dict = dict()

    wd = webdriver.Chrome('chromedriver', options=chrome_options)
    google_url = 'https://www.google.com'
    
    for i in range(len(df)):
        query = '{} {} game genre'.format(df.iloc[i, 1], re.sub('[\(\[].*?[\)\]]', '', df.iloc[i, 0]).strip())
        wd.get(google_url + '/search?q={}'.format(query))
        class_name = 'Z0LcW'

        try:
            genre_element = wd.find_element_by_class_name(class_name)
            
            wait = WebDriverWait(wd, 10)

            wait.until(EC.visibility_of(genre_element))

            genre_text = genre_element.text

            g_dict[df.iloc[i, 0]] = genre_text

        except Exception as e:
            pass

    wd.close()

    return g_dict


def fill_genre(df, split):

    rst_dict = dict()

    df_dict = {n: df.iloc[n:n+split, :] for n in range(0, len(df), split)}

    for key in df_dict.keys():
        rst_dict.update(get_genre(df_dict[key]))

    return rst_dict